### ISSUE TITLE
AbstractBigMathFunction.evaluate() causes NoSuchMethodError

### ISSUE THREAD

**Issue by mvsoder** [ezylang/EvalEx#510]
When an expression calls AbstractBigMathFunction.evaluate() a NoSuchMethodError is thrown.

```
    java.lang.NoSuchMethodError: 'void com.ezylang.evalex.data.EvaluationValue.<init>(java.lang.Object)'
        at com.ezylang.evalex.bigmath.functions.bigdecimalmath.AbstractBigMathFunction.evaluate(AbstractBigMathFunction.java:48)
        at com.ezylang.evalex.Expression.evaluateFunction(Expression.java:191)
        at com.ezylang.evalex.Expression.evaluateSubtree(Expression.java:147)
        at com.ezylang.evalex.Expression.evaluateFunction(Expression.java:181)
        at com.ezylang.evalex.Expression.evaluateSubtree(Expression.java:147)
        at com.ezylang.evalex.Expression.evaluate(Expression.java:89)
```
Java 17
Using EvalEx 3.4.0
Used to work on EvalEx 3.2.0

**Comment by uklimaschewski** [comment]
I have just published [EvalEx-big-math](https://github.com/ezylang/EvalEx-big-math) version 1.0.1 which fixes that problem.
